version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"  # UI port
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "4317:4317"    # OTLP gRPC port
      - "4318:4318"    # OTLP HTTP port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - tracing-network

networks:
  tracing-network:
    driver: bridge

volumes:
  redis_data:
