name: ray-serve-dlrm-benchmark-service

image_uri: anyscale/image/ray-serve-dlrm-benchmark-service:1

compute_config:
  head_node:
    instance_type: m5.2xlarge
  worker_nodes:
    - instance_type: g6.12xlarge # 4 GPUs, 48 vCPUs, 192 GB RAM
      min_nodes: 1
      max_nodes: 4
      market_type: ON_DEMAND

working_dir: .

cloud: anyscale_v2_default_cloud

applications:
- import_path: app:recsys_app
  runtime_env:
    pip:
      - torch
      - numpy
  deployments:
    - name: ranker_deployment
      num_replicas: 1
      max_ongoing_requests: 1000
      ray_actor_options:
        num_gpus: 1
    - name: candidate_generator
      num_replicas: 1
      max_ongoing_requests: 1000
    - name: ingress_deployment
      num_replicas: 1
      max_ongoing_requests: 1000
